name: 'Stop Runner '
description: 'Stops the AWS runner'
inputs:
  os:
    required: true
    type: string
  label:
    required: true
    type: string
  ec2-instance-id:
    required: true
    type: string
  aws-region:
    required: true
    type: string
  aws-role-to-assume:
    required: true
    type: string
  aws-role-session-name:
    required: true
    type: string
  
  # Used as local variables. Don't need to pass
  deregister-runner-timeout:
    required: false
    default: 7
    type: number
  aws-availability-zone:
    required: false
    default: us-east-1b
    type: string
  

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-role-session-name }}
        aws-region: ${{ inputs.aws-region }}
    
    - id: gh-token # Fetch github-token from aws-ssm
      name: Git Describe
      uses: febiosoftware/febio-workflows/.github/actions/github-token@develop
    
    - name: Stop EC2 runner
      uses: febiosoftware/ec2-multiple-github-runners@multi-os-multi-runner
      with:
        mode: stop
        os: ${{ inputs.os }}
        wait-for-deregistry-timeout: ${{ inputs.deregister-runner-timeout }}
        github-token: ${{ steps.gh-token.outputs.token}}
        label: ${{ inputs.label }}
        ec2-instance-id: ${{ inputs.ec2-instance-id }}

