name: 'Git Describe'
description: 'Gets the version number from git describe'
inputs:
  shell:
    require: true
    type: string
  path:
    require: false
    type: string
    default: "."
outputs:
  git_describe:
    value: ${{ steps.git-describe.outputs.git_describe }}
  git_describe_stripped:
    value: ${{ steps.git-describe.outputs.git_describe_stripped }}

runs:
  using: "composite"
  steps:
    - id: git-describe
      shell: ${{inputs.shell}}
      run: |
        pushd ${{inputs.path}}
        git fetch --tags --force
        git_describe=$(git describe || git rev-parse --short HEAD)
        echo "git_describe=$git_describe"
        echo "git_describe=$git_describe" >> "$GITHUB_OUTPUT"

        git_describe_stripped=${git_describe:1} # strip the 'v' from the front
        git_describe_stripped=${git_describe_stripped%%-*} # strip off everything at or after the first -

        echo "git_describe_stripped=$git_describe_stripped"
        echo "git_describe_stripped=$git_describe_stripped" >> "$GITHUB_OUTPUT"
        popd
