name: 'Build'
description: 'Builds project and uploads artifacts'
inputs:
  shell:
    require: true
    type: string
  path:
    require: false
    type: string
    default: "."
outputs:
  git_describe:
    value: ${{ steps.git-describe.outputs.git_describe }}
  git_describe_stripped:
    value: ${{ steps.git-describe.outputs.git_describe_stripped }}

runs:
  using: "composite"
  steps:
    - id: git-describe
      shell: ${{inputs.shell}}
      run: |
        pushd ${{inputs.path}}
        git_describe=$(git describe || git rev-parse --short HEAD)
        echo "git_describe=$git_describe" >> "$GITHUB_OUTPUT"
        echo "git_describe_stripped=${git_describe:1}" >> "$GITHUB_OUTPUT"
        echo $git_describe
        echo ${git_describe:1}
        popd
