name: 'Release'
description: 'Runs release script and uploads artifacts'
inputs:
  febioVer:
    required: true
    type: string
  fbsVer:
    required: true
    type: string
  shell:
    require: true
    type: string
  os:
    required: true
    type: string
  ib_license_file:
    required: true
    type: string
  ib_license_contents:
    required: true
    type: string
  releaseDir:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Write License File
      shell: ${{inputs.shell}}
      run: |
        echo $IB_LICENSE_CONTENTS >> $IB_LICENSE_FILE
      env:
        IB_LICENSE_FILE: ${{inputs.ib_license_file}}
        IB_LICENSE_CONTENTS: ${{inputs.ib_license_contents}}
    - name: Release Script
      shell: ${{inputs.shell}}
      run: |
        ci/${{inputs.os}}/release.sh
      env:
        FEBIO_VER: ${{inputs.febioVer}}
        FBS_VER: ${{inputs.fbsVer}}
    - name: Build
      shell: ${{inputs.shell}}
      run: |
        ${{ inputs.script }}
    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.os}}-Release-Artifacts
        path: |
          ${{inputs.releaseDir}}/bin
          ${{inputs.releaseDir}}/febioLib
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: FEBioStudio_${{inputs.fbsVer}}_FEBio_${{inputs.febioVer}}_${{inputs.os}}_installer
        path: |
          ${{inputs.releaseDir}}/installer/*
    