name: 'Release'
description: 'Runs release script and uploads artifacts'
inputs:
  febioVer:
    required: true
    type: string
  fbsVer:
    required: true
    type: string
  shell:
    require: true
    type: string
  script:
    required: true
    type: string
  os:
    required: true
    type: string
  ib_license_contents:
    required: true
    type: string
  osxKeyPswd:
    required: false
    type: string
    default: 
runs:
  using: "composite"
  steps:
    - name: Write License File
      shell: bash
      run: |
        echo $IB_LICENSE_CONTENTS > license.xml
      env:
        IB_LICENSE_CONTENTS: ${{inputs.ib_license_contents}}
    - name: Release Script
      shell: ${{inputs.shell}}
      run: |
        ${{ inputs.script }}
      env:
        FEBIO_VER: ${{inputs.febioVer}}
        FBS_VER: ${{inputs.fbsVer}}
        OSXSIGN: ${{inputs.osxKeyPswd}}
    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.os}}-Release-Artifacts
        path: |
          ${{github.workspace}}/upload/bin
          ${{github.workspace}}/upload/lib
          ${{github.workspace}}/upload/doc
          ${{github.workspace}}/upload/MacOS
          ${{github.workspace}}/upload/Frameworks
          ${{github.workspace}}/upload/sdk.zip
    - name: Upload Updater
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.os}}-Updater-Artifacts
        path: |
          ${{github.workspace}}/upload/updater/*
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: FEBioStudio_${{inputs.fbsVer}}_FEBio_${{inputs.febioVer}}_${{inputs.os}}_installer
        path: |
          ${{github.workspace}}/upload/installer/*
    