name: 'Download SDK'
description: 'Fetches SDK FROM AWS'
inputs:
  shell:
    required: false
    default: bash
    type: string
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  sdk-config:
    required: false
    type: string
    default: "{ }"
outputs:
  febio-version:
    value: ${{ steps.get-version.outputs.febio-version }}

runs:
  using: "composite"
  steps:
    - name: Get Inputs
      if: ${{inputs.sdk-config}}
      id: sdk-config
      shell: ${{inputs.shell}}
      run: |
        echo "package_branch=${{fromJson(inputs.sdk-config).package_branch}}" >> $GITHUB_OUTPUT
        echo "package_path=${{fromJson(inputs.sdk-config).package_path}}" >> $GITHUB_OUTPUT
        echo "package=${{fromJson(inputs.sdk-config).package}}" >> $GITHUB_OUTPUT
        echo "bucket=${{fromJson(inputs.sdk-config).bucket}}" >> $GITHUB_OUTPUT
    - name: Fetch latest febio-sdk
      shell: ${{inputs.shell}}
      run: |
        ci/common/get-febio-sdk.sh
      env:
        OS: ${{inputs.os}}
        PACKAGE_BRANCH: ${{steps.sdk-config.outputs.package_branch}}
        PACKAGE_PATH: ${{steps.sdk-config.outputs.package_path}}
        PACKAGE: ${{steps.sdk-config.outputs.package}}
        BUCKET: ${{steps.sdk-config.outputs.bucket}}
    - name: Extract SDK version
      id: get-version
      shell: bash
      run: |
        major=$(grep '#define VERSION' sdk/include/FEBioLib/version.h | awk '{print $3}')
        minor=$(grep '#define SUBVERSION' sdk/include/FEBioLib/version.h | awk '{print $3}')
        patch=$(grep '#define SUBSUBVERSION' sdk/include/FEBioLib/version.h | awk '{print $3}')
        echo "febio-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
