name: 'Download SDK'
description: 'Fetches SDK From SCI and extracts version information'
inputs:
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
outputs:
  febio-version:
    value: ${{ steps.get-version.outputs.febio-version }}

runs:
  using: "composite"
  steps:
    - name: Fetch latest febio-sdk
      shell: bash
      run: |
        scp shell:/uufs/sci.utah.edu/projects/Weiss/ci/sdk/febio4-sdk-${{inputs.os}}-${{inputs.arch}}.zip ./sdk.zip
        unzip sdk.zip -d ./febio4-sdk
    - name: Extract SDK version
      id: get-version
      shell: bash
      run: |
        major=$(grep '#define VERSION' febio4-sdk/include/FEBioLib/version.h | awk '{print $3}')
        minor=$(grep '#define SUBVERSION' febio4-sdk/include/FEBioLib/version.h | awk '{print $3}')
        patch=$(grep '#define SUBSUBVERSION' febio4-sdk/include/FEBioLib/version.h | awk '{print $3}')
        echo "febio-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
