name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  os:
    required: true
    type: string
  febioVer:
    required: true
    type: string
  fbsVer:
    required: true
    type: string
  ssh-user:
    required: true
    type: string
  ssh-key:
    required: true
    type: string
  ssh-host:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{inputs.os}}-Release-Artifacts
        path: |
          artifacts
    - name: Configure SSH
      shell: bash
      run: |
        ci/common/linux/configure-ssh.sh
      env:
        SSH_USER: ${{ inputs.ssh-user }}
        SSH_KEY: ${{ inputs.ssh-key }}
        SSH_HOST: ${{ inputs.ssh-host }}
    - name: Stage Build to Repo
      shell: bash
      run: |
        ci/${{inputs.os}}/scp-to-repo-release.sh
    - name: Make Release
      shell: bash
      run: |
        ssh repo "python3 /home/febio-github/modelServer/makeRelease.py ${{inputs.os}} ${{inputs.febioVer}} ${{inputs.fbsVer}}"
