name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  febioVer:
    required: true
    type: string
  fbsVer:
    required: true
    type: string
  ssh-user:
    required: true
    type: string
  ssh-key:
    required: true
    type: string
  ssh-host:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v8
      with:
        name: ${{inputs.os}}-Release-Artifacts
        path: |
          artifacts
    - name: Download Plugins
      uses: actions/download-artifact@v8
      with:
        name: plugins-${{inputs.os}}-${{inputs.arch}}
        path: |
          plugins
    - name: Stage Build to Repo
      shell: bash
      run: |
        ci/${{inputs.os}}/scp-to-repo-release.sh
    - name: Make Release
      shell: bash
      run: |
        ssh repo "python3 /serverCode/serverTools/makeRelease.py ${{inputs.os}} ${{inputs.febioVer}} ${{inputs.fbsVer}}"
    - name: Push and update plugins
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          python.exe ci/common/repo-plugins.py
        else
          python3 ci/common/repo-plugins.py
        fi
      env:
        OS: ${{ inputs.os }}
        DEV_RELEASE: 0
