name: 'Uplaods Plugins'
description: 'Gathers and uploads plugins'
inputs:
  os:
    required: true
    type: string
  arch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout ci-common 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: febiosoftware/ci-common
        path: common
    - name: Gather plugins
      shell: bash
      env:
        FEBIO_SDK: febio4-sdk
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          python.exe common/gather-plugins.py
        else
          python3 common/gather-plugins.py
        fi
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugins-${{inputs.os}}-${{inputs.arch}}
        path: |
          plugins
