name: 'Upload '
description: 'Creates SDK and Uploads artifacts'
inputs:
  runTests:
    description: "Run tests?"
    required: false
    type: boolean
    default: false
  python-module:
    required: false
    type: boolean
    default: false
  package-sdk:
    default: false
    required: false
    type: boolean
  shell:
    require: false
    type: string
  package-name:
    required: true
    type: string
  os:
    required: true
    type: string
  plugin:
    default: false
    required: false
    type: boolean
  febio-version:
    default: ""
    required: false
    type: string
  arch:
    required: true
    type: string
  ssh-user:
    required: true
    type: string
  ssh-key:
    required: true
    type: string
  ssh-host:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      if: ${{ inputs.python-module == 'false' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          cmbuild
    - name: Download SDK
      if: ${{ inputs.package-sdk == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-sdk-${{inputs.os}}-${{inputs.arch}}
        path: |
          sdk
    - name: Configure SSH
      shell: ${{inputs.shell}}
      run: |
        ci/common/configure-ssh.sh
      env:
        SSH_USER: ${{ inputs.ssh-user }}
        SSH_KEY: ${{ inputs.ssh-key }}
        SSH_HOST: ${{ inputs.ssh-host }}
    - name: Get OS Argument
      id: os-argument
      shell: ${{inputs.shell}}
      run: |
        OS=${{inputs.os}}
        case $OS in

          macOS)
            OS_ARG="-m"
            ;;

          Windows)
            OS_ARG="-w"
            ;;

          Linux)
            OS_ARG="-l"
            ;;

          *)
            echo "unknown"; exit 1
            ;;

        esac
        echo "os-arg=$OS_ARG" >> $GITHUB_OUTPUT
    - name: Make Dev Release
      if: ${{ inputs.plugin == 'false' && inputs.python-module == 'false' }}
      uses: febiosoftware/febio-workflows/.github/actions/make-dev-release@develop
      with:
        runTests: ${{ inputs.runTests  == 'true' }}
        python-module: ${{ inputs.python-module }}
        os: ${{ inputs.os }}
        os-arg: ${{ steps.os-argument.outputs.os-arg }}
        arch: ${{ inputs.arch }}
    - name: Make Plugin Release
      if: ${{ inputs.plugin == 'true' }}
      uses: febiosoftware/febio-workflows/.github/actions/make-plugin-release@develop
      with:
        os-arg: ${{ steps.os-argument.outputs.os-arg }}
        febio-version: ${{ inputs.febio-version }}
        dev-flag: -d
    - name: Download Python Module
      uses: actions/download-artifact@v4
      if: ${{ inputs.python-module == 'true' }}
      with:
        name: fbs-python-${{inputs.os}}-${{inputs.arch}}
        path: |
          pythonModule
    - name: Push Python Module
      if: ${{ inputs.python-module == 'true' }}
      shell: bash
      run: |
        ci/${{inputs.os}}/scp-python-module.sh
