name: 'Upload '
description: 'Creates SDK and Uploads artifacts'
inputs:
  runTests:
    description: "Run tests?"
    required: false
    type: boolean
    default: false
  shell:
    require: false
    type: string
  package-name:
    required: true
    type: string
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  ssh-user:
    required: true
    type: string
  ssh-key:
    required: true
    type: string
  ssh-host:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          cmbuild
    - name: Download test suite logs
      uses: actions/download-artifact@v4
      if: ${{ inputs.runTests == 'true' }}
      continue-on-error: true
      with:
        name: testsuite-${{inputs.os}}-${{inputs.arch}}-logs
        path: |
          testLogs
    - name: Download FEBioChem
      uses: actions/download-artifact@v4
      if: ${{ inputs.runTests == 'true' }}
      continue-on-error: true
      with:
        name: FEBioChem-${{inputs.os}}-${{inputs.arch}}
        path: |
          ChemArtifacts
    - name: Download FEBioHeat
      uses: actions/download-artifact@v4
      if: ${{ inputs.runTests == 'true' }}
      continue-on-error: true
      with:
        name: FEBioHeat-${{inputs.os}}-${{inputs.arch}}
        path: |
          HeatArtifacts
    - name: Configure SSH
      shell: ${{inputs.shell}}
      run: |
        ci/common/linux/configure-ssh.sh
      env:
        SSH_USER: ${{ inputs.ssh-user }}
        SSH_KEY: ${{ inputs.ssh-key }}
        SSH_HOST: ${{ inputs.ssh-host }}
    - name: Extract branch name
      shell: ${{inputs.shell}}
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Prep Branch Paths
      shell: ${{inputs.shell}}
      run: |
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 update2/FEBioStudio2Dev/prepBranchPaths.py $BRANCH"
    - name: Stage Build to Repo
      shell: ${{inputs.shell}}
      run: |
        ci/${{inputs.os}}/scp-to-repo.sh ${{ steps.extract_branch.outputs.branch }}
    - name: Get OS Argument
      id: os-argument
      shell: ${{inputs.shell}}
      run: |
        OS=${{inputs.os}}
        case $OS in

          macOS)
            OS_ARG="-m"
            ;;

          Windows)
            OS_ARG="-w"
            ;;

          Linux)
            OS_ARG="-l"
            ;;

          *)
            echo "unknown"; exit 1
            ;;

        esac
        echo "os-arg=$OS_ARG" >> $GITHUB_OUTPUT

    - name: Make Dev Release
      shell: ${{inputs.shell}}
      run: |
        OS_ARG=${{steps.os-argument.outputs.os-arg}}
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 update2/FEBioStudio2Dev/makeDevRelease.py $OS_ARG $BRANCH"
