name: 'Make Dev Release '
description: 'Uploads artifacts and makes dev release'
inputs:
  runTests:
    description: "Run tests?"
    required: false
    type: boolean
    default: false
  os:
    required: true
    type: string
  os-arg:
    required: true
    type: string
  arch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download test suite logs
      uses: actions/download-artifact@v4
      if: ${{ inputs.runTests == 'true' }}
      continue-on-error: true
      with:
        name: testsuite-${{inputs.os}}-${{inputs.arch}}-logs
        path: |
          testLogs
    - name: Download Plugins
      uses: actions/download-artifact@v4
      if: ${{ inputs.runTests == 'true' }}
      continue-on-error: true
      with:
        name: plugins-${{inputs.os}}-${{inputs.arch}}
        path: |
          plugins
    - name: Extract branch name
      shell: bash
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Prep Branch Paths
      shell: bash
      run: |
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 update2/FEBioStudio2Dev/prepBranchPaths.py $BRANCH"
    - name: Stage Build to Repo
      shell: bash
      run: |
        ci/${{inputs.os}}/scp-to-repo.sh ${{ steps.extract_branch.outputs.branch }}
    - name: Make Dev Release
      shell: bash
      run: |
        OS_ARG=${{ inputs.os-arg }}
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 update2/FEBioStudio2Dev/makeDevRelease.py $OS_ARG $BRANCH"
    - name: Push and update plugins
      if: ${{ inputs.runTests == 'true' }}
      shell: bash
      run: |
          python3 ci/common/repo-plugins.py
      env:
        OS: ${{ inputs.os }}
        DEV_RELEASE: 1
