name: 'Make Dev Release '
description: 'Uploads artifacts and makes dev release'
inputs:
  os:
    required: true
    type: string
  os-arg:
    required: true
    type: string
  arch:
    required: true
    type: string
  build-plugins:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Extract branch name
      shell: bash
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Prep Branch Paths
      shell: bash
      run: |
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 /serverCode/serverTools/prepBranchPaths.py $BRANCH"
    - name: Stage Build to Repo
      shell: bash
      run: |
        ci/${{inputs.os}}/scp-to-repo.sh ${{ steps.extract_branch.outputs.branch }}
    - name: Make Dev Release
      shell: bash
      run: |
        OS_ARG=${{ inputs.os-arg }}
        BRANCH=${{ steps.extract_branch.outputs.branch }}
        ssh repo "python3 /serverCode/serverTools/makeDevRelease.py $OS_ARG $BRANCH"
    - name: Download Plugins
      uses: actions/download-artifact@v8
      if: ${{ inputs.build-plugins == 'true' }}
      with:
        name: plugins-${{inputs.os}}-${{inputs.arch}}
        path: |
          plugins
    - name: Push and update plugins
      if: ${{ inputs.build-plugins == 'true' && steps.extract_branch.outputs.branch == 'develop' }}
      shell: bash
      run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            python.exe ci/common/repo-plugins.py
          else
            python3 ci/common/repo-plugins.py
          fi
      env:
        OS: ${{ inputs.os }}
        DEV_RELEASE: 1
