on:
  workflow_call:
    inputs:
      shell:
        required: false
        default: bash
        type: string
      package-name:
        required: true
        type: string
      package-sdk:
        default: false
        required: false
        type: boolean
      requires-sdk:
        default: false
        required: false
        type: boolean
      sdk-config:
        required: false
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
      aws-region:
        default: us-east-1
        required: false
        type: string
      aws-role-to-assume:
        required: false
        default: arn:aws:iam::353328028284:role/github-actions-runner
        type: string
      aws-role-session-name:
        required: false
        default: febio-github-actions-runner-session
        type: string
      aws-availability-zone:
        required: false
        default: us-east-1b
        type: string
      post-build:
        required: false
        type: boolean
        default: false

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: Clone and build
    runs-on: self-hosted
    outputs:
      git_describe: ${{ steps.git-describe.outputs.git_describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - id: git-describe
        name: Git Describe
        uses: febiosoftware/febio-workflows/.github/actions/git-describe@develop
        with:
          shell: ${{ inputs.shell }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-session-name: ${{ inputs.aws-role-session-name }}
          aws-region: ${{ inputs.aws-region }}
      - name: Build
        uses: febiosoftware/febio-workflows/.github/actions/build@develop
        with:
          post-build: ${{ inputs.post-build }}
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          requires-sdk: ${{ inputs.requires-sdk }}
          sdk-config: ${{ inputs.sdk-config }}
          package-sdk: ${{ inputs.package-sdk }}
          script: ci/${{inputs.os}}/build.sh
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
  tests:
    if: ${{ (inputs.runTests) && (env.BRANCH_NAME == 'develop') }}
    name: Run test suite
    needs:
      - build
    runs-on: self-hosted
    steps:
      - name: Download SDK
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package-name }}-sdk-${{inputs.os}}-${{inputs.arch}}
          path: |
            febio4-sdk
      - name: Checkout FEBioChem
        uses: actions/checkout@v4
        with:
          path: FEBioChem
          repository: febiosoftware/FEBioChem
          ref: develop
      - name: Checkout FEBioHeat
        uses: actions/checkout@v4
        with:
          path: FEBioHeat
          repository: febiosoftware/FEBioHeat
          ref: develop
      - name: Build FEBioChem
        uses: febiosoftware/febio-workflows/.github/actions/build@develop
        with:
          shell: ${{ inputs.shell }}
          repo-dir: FEBioChem
          package-name: FEBioChem
          script: FEBioChem/ci/${{inputs.os}}/build.sh
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          aws-region: ${{ inputs.aws-region }}
      - name: Build FEBioHeat
        uses: febiosoftware/febio-workflows/.github/actions/build@develop
        with:
          shell: ${{ inputs.shell }}
          repo-dir: FEBioHeat
          package-name: FEBioHeat
          script: FEBioHeat/ci/${{inputs.os}}/build.sh
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          aws-region: ${{ inputs.aws-region }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-session-name: ${{ inputs.aws-role-session-name }}
          aws-region: ${{ inputs.aws-region }}
      - name: Tests
        uses: febiosoftware/febio-workflows/.github/actions/run-tests@develop
        with:
          script: ci/${{inputs.os}}/test.sh
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          git-token: ${{ secrets.TESTSUITE_WRITE }}
  repo-artifacts:
    name: Upload artifacts to repo
    needs:
      - build
      - tests
    runs-on: ubuntu-latest
    if: >
      always() &&
      contains(fromJson('["success"]'), needs.build.result) &&
      contains(fromJson('["success", "skipped"]'), needs.tests.result) &&
      ! github.event.pull_request.head.repo.fork
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Repo Artifacts
        uses: febiosoftware/febio-workflows/.github/actions/repo-artifacts@develop
        with:
          runTests: ${{ inputs.runTests }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
  publish-to-s3:
    name: Publish to S3
    needs:
      - build
      - tests
    runs-on: ubuntu-latest
    if: >
      always() &&
      contains(fromJson('["success"]'), needs.build.result) &&
      contains(fromJson('["success", "skipped"]'), needs.tests.result) &&
      ! github.event.pull_request.head.repo.fork
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          role-session-name: ${{ inputs.aws-role-session-name }}
          aws-region: ${{ inputs.aws-region }}
      - name: Publish To S3
        uses: febiosoftware/febio-workflows/.github/actions/publish-to-s3@develop
        with:
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          package-sdk: ${{ inputs.package-sdk }}
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          git-tag: ${{ needs.build.outputs.git_describe }}
