on:
  workflow_call:
    inputs:
      febioVer:
        required: true
        type: string
      fbsVer:
        required: true
        type: string
      shell:
        required: false
        default: bash
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release
    runs-on: self-hosted
    outputs:
      febio_git_describe: ${{ steps.describe_febio.outputs.git_describe_stripped }}
      fbs_git_describe: ${{ steps.describe_fbs.outputs.git_describe_stripped }}
    steps:
      - name: Checkout FBS
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: FEBioStudio
          ref: develop
      - name: Checkout FEBio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: FEBio
          repository: febiosoftware/FEBio
          ref: develop
      - name: Checkout FEBioChem
        uses: actions/checkout@v4
        with:
          path: FEBioChem
          repository: febiosoftware/FEBioChem
          ref: develop
      - name: Checkout FEBioHeat
        uses: actions/checkout@v4
        with:
          path: FEBioHeat
          repository: febiosoftware/FEBioHeat
          ref: develop
      - name: Describe FEBio
        uses: febioSoftware/febio-workflows/.github/actions/git-describe@develop
        id: describe_febio
        with:
          path: FEBio
      - name: Describe FBS
        uses: febioSoftware/febio-workflows/.github/actions/git-describe@develop
        id: describe_fbs
        with:
          path: FEBioStudio
      - name: Release
        uses: febiosoftware/febio-workflows/.github/actions/release@develop
        with:
          febioVer: ${{ steps.describe_febio.outputs.git_describe_stripped }}
          fbsVer: ${{ steps.describe_fbs.outputs.git_describe_stripped }}
          shell: ${{ inputs.shell }}
          script: FEBioStudio/ci/${{inputs.os}}/release.sh
          os: ${{inputs.os}}
          ib_license_contents: ${{ secrets.INSTALL_BUILDER_LICENSE }}
          macos_pkcs12_pswd: ${{ secrets.MACOS_PKCS12_PSWD }}
          macos_sign_id: ${{ secrets.MACOS_SIGN_ID }}
          macos_sign_pwd: ${{ secrets.MACOS_SIGN_PWD }}
          macos_sign_team: ${{ secrets.MACOS_SIGN_TEAM }}
  repo-artifacts:
    name: Upload artifacts to repo
    needs:
      - release # required to get output from the start-runner job
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Repo Artifacts
        uses: febiosoftware/febio-workflows/.github/actions/repo-artifacts-release@develop
        with:
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          os: ${{inputs.os}}
          febioVer: ${{ needs.release.outputs.febio_git_describe }}
          fbsVer: ${{ needs.release.outputs.fbs_git_describe }}
