on:
  workflow_call:
    inputs:
      febioVer:
        required: true
        type: string
      fbsVer:
        required: true
        type: string
      shell:
        required: false
        default: bash
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release
    runs-on: self-hosted
    outputs:
      git_describe: ${{ steps.git-describe.outputs.git_describe }}
    steps:
      - name: Checkout FBS
        uses: actions/checkout@v4
        with:
          path: FEBioStudio
          ref: ci/develop
      - name: Checkout FEBio
        uses: actions/checkout@v4
        with:
          path: FEBio
          repository: febiosoftware/FEBio
          ref: ci/develop
      - name: Checkout FEBioChem
        uses: actions/checkout@v4
        with:
          path: FEBioChem
          repository: febiosoftware/FEBioChem
          ref: ci/develop
      - name: Checkout FEBioHeat
        uses: actions/checkout@v4
        with:
          path: FEBioHeat
          repository: febiosoftware/FEBioHeat
          ref: ci/develop
      - name: Release
        uses: febiosoftware/febio-workflows/.github/actions/release@develop
        with:
          febioVer: ${{ inputs.febioVer }}
          fbsVer: ${{ inputs.fbsVer }}
          shell: ${{ inputs.shell }}
          script: FEBioStudio/ci/${{inputs.os}}/release.sh
          os: ${{inputs.os}}
          ib_license_contents: ${{ secrets.INSTALL_BUILDER_LICENSE }}
          osxKeyPswd: ${{ secrets.MACOS_PKCS12_PSWD }}
  # tests:
  #   if: inputs.runTests
  #   name: Run test suite
  #   needs:
  #     - build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: 'true'
  #     - name: Tests
  #       uses: febiosoftware/febio-workflows/.github/actions/run-tests@develop
  #       with:
  #         script: ci/${{inputs.os}}/test.sh
  #         shell: ${{ inputs.shell }}
  #         package-name: ${{ inputs.package-name }}
  #         os: ${{inputs.os}}
  #         arch: ${{inputs.arch}}
  repo-artifacts:
    name: Upload artifacts to repo
    needs:
      - release # required to get output from the start-runner job
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Repo Artifacts
        uses: febiosoftware/febio-workflows/.github/actions/repo-artifacts-release@develop
        with:
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          os: ${{inputs.os}}
          febioVer: ${{ inputs.febioVer }}
          fbsVer: ${{ inputs.fbsVer }}
