on:
  workflow_call:
    inputs:
      shell:
        required: false
        default: bash
        type: string
      package-name:
        required: true
        type: string
      plugin-name:
        default: ""
        required: false
        type: string
      package-sdk:
        default: false
        required: false
        type: boolean
      requires-sdk:
        default: false
        required: false
        type: boolean
      sdk-config:
        required: false
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      build-script:
        default: build.sh
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
      publish:
        required: false
        type: boolean
        default: false
      build-plugins:
        description: "Build all plugins?"
        required: false
        type: boolean
        default: false
      dev-release:
        description: "Make a dev release?"
        required: false
        type: boolean
        default: true
      python-module:
        description: "Compile Python Module?"
        required: false
        type: boolean
        default: false
      post-build:
        required: false
        type: boolean
        default: false
      plugin:
        description: "Is this a plugin repo?"
        required: false
        type: boolean
        default: false

concurrency:
  group: macos-build
  cancel-in-progress: false

jobs:
  build:
    name: Clone and build
    runs-on: [self-hosted, macOS]
    outputs:
      febio-version: ${{ steps.build.outputs.febio-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build
        id: build
        uses: febiosoftware/febio-workflows/.github/actions/build@certTest
        with:
          post-build: ${{ inputs.post-build }}
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          requires-sdk: ${{ inputs.requires-sdk }}
          package-sdk: ${{ inputs.package-sdk }}
          script: ci/${{inputs.os}}/${{inputs.build-script}}
          python-module: ${{ inputs.python-module }}
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          macos_pkcs12_pswd: ${{ secrets.MACOS_PKCS12_PSWD }}
          macos_keychain: ${{ secrets.MACOS_KEYCHAIN }}
          macos_keychain_password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
          macos_sign: ${{ secrets.MACOS_SIGN }} 
      # - name: Get plugin repos
      #   if: inputs.build-plugins
      #   id: get-plugin-repos
      #   uses: febiosoftware/febio-workflows/.github/actions/get-plugin-repos@develop
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout plugin repos
      #   if: inputs.build-plugins
      #   uses: febiosoftware/febio-workflows/.github/actions/checkout-plugins@develop
      #   with:
      #     repo_list: ${{ steps.get-plugin-repos.outputs.repo_list }}
      # - name: Build plugins
      #   if: inputs.build-plugins
      #   uses: febiosoftware/febio-workflows/.github/actions/build-plugins@develop
      #   with:
      #     repo_list: ${{ steps.get-plugin-repos.outputs.repo_list }}
      # - name: Upload plugins 
      #   if: inputs.build-plugins
      #   uses: febiosoftware/febio-workflows/.github/actions/upload-plugins@develop
      #   with:
      #     os: ${{inputs.os}}
      #     arch: ${{inputs.arch}}
  
  # tests:
  #   if: inputs.runTests
  #   name: Run test suite
  #   needs:
  #     - build
  #   runs-on: [self-hosted, macOS]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #       with:
  #         fetch-depth: 1
  #         submodules: true
  #     - name: Tests
  #       uses: febiosoftware/febio-workflows/.github/actions/run-tests@develop
  #       with:
  #         script: ci/${{inputs.os}}/test.sh
  #         shell: ${{ inputs.shell }}
  #         package-name: ${{ inputs.package-name }}
  #         os: ${{inputs.os}}
  #         arch: ${{inputs.arch}}
  #         build-plugins: ${{ inputs.build-plugins }}
  #         git-test-suite-token: ${{ secrets.TESTSUITE_WRITE }}
  #         git-token: ${{ secrets.GITHUB_TOKEN }}
  
  # publish:
  #   name: Publish
  #   needs:
  #     - build
  #     - tests
  #   runs-on: [self-hosted, macOS]
  #   if: >
  #     ${{
  #       always() && inputs.publish &&
  #       contains(fromJson('["success"]'), needs.build.result) &&
  #       contains(fromJson('["success", "skipped"]'), needs.tests.result) &&
  #       !github.event.pull_request.head.repo.fork
  #     }}
  #   steps:
  #     - name: Repo Artifacts
  #       uses: febiosoftware/febio-workflows/.github/actions/repo-artifacts@develop
  #       with:
  #         build-plugins: ${{ inputs.build-plugins }}
  #         dev-release: ${{ inputs.dev-release }}
  #         python-module: ${{ inputs.python-module }}
  #         package-sdk: ${{ inputs.package-sdk }}
  #         shell: ${{ inputs.shell }}
  #         package-name: ${{ inputs.package-name }}
  #         os: ${{inputs.os}}
  #         arch: ${{inputs.arch}}
  #         plugin: ${{inputs.plugin}}
  #         febio-version: ${{ needs.build.outputs.febio-version }}
  #     - name: Publish SDK
  #       if: ${{ inputs.package-sdk }}
  #       run: |
  #         scp sdk/sdk.zip shell:/uufs/sci.utah.edu/projects/Weiss/ci/sdk/${{ inputs.package-name }}-sdk-${{inputs.os}}-${{inputs.arch}}.zip