on:
  workflow_call:
    inputs:
      shell:
        required: false
        default: bash
        type: string
      os:
        default: Windows
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string

concurrency:
  group: windows-build
  cancel-in-progress: false

jobs:
  release:
    name: Run release script
    runs-on: [self-hosted, Windows] # run the job on the newly created runner
    outputs:
      febio_git_describe: ${{ steps.describe_febio.outputs.git_describe_stripped }}
      fbs_git_describe: ${{ steps.describe_fbs.outputs.git_describe_stripped }}
    steps:
      - name: Checkout FBS
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: FEBioStudio
          ref: master
      - name: Checkout FEBio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: FEBio
          repository: febiosoftware/FEBio
          ref: master
      - name: Describe FEBio
        uses: febioSoftware/febio-workflows/.github/actions/git-describe@test
        id: describe_febio
        with:
          shell: bash
          path: FEBio
      - name: Describe FBS
        uses: febioSoftware/febio-workflows/.github/actions/git-describe@test
        id: describe_fbs
        with:
          shell: bash
          path: FEBioStudio
      - name: Release
        uses: febiosoftware/febio-workflows/.github/actions/release@test
        with:
          febioVer: ${{ steps.describe_febio.outputs.git_describe_stripped }}
          fbsVer: ${{ steps.describe_fbs.outputs.git_describe_stripped }}
          shell: powershell
          script: FEBioStudio/ci/${{inputs.os}}/release.ps1
          os: ${{inputs.os}}
          ib_license_contents: ${{ secrets.INSTALL_BUILDER_LICENSE }}
      - name: Get plugin repos
        id: get-plugin-repos
        uses: febiosoftware/febio-workflows/.github/actions/get-plugin-repos@test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout plugin repos
        uses: febiosoftware/febio-workflows/.github/actions/checkout-plugins@test
        with:
          repo_list: ${{ steps.get-plugin-repos.outputs.repo_list }}
      - name: Build plugins
        uses: febiosoftware/febio-workflows/.github/actions/build-plugins@test
        with:
          repo_list: ${{ steps.get-plugin-repos.outputs.repo_list }}
      - name: Upload plugins 
        uses: febiosoftware/febio-workflows/.github/actions/upload-plugins@test
        with:
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
  
  repo-artifacts:
    name: Upload artifacts to repo
    needs:
      - release # required to get output from the start-runner job
    runs-on: [self-hosted, Windows]
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Repo Artifacts
        uses: febiosoftware/febio-workflows/.github/actions/repo-artifacts-release@test
        with:
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          os: ${{inputs.os}}
          arch: ${{ inputs.arch }}
          febioVer: ${{ needs.release.outputs.febio_git_describe }}
          fbsVer: ${{ needs.release.outputs.fbs_git_describe }}
